ALTER TABLE `posts`
  ADD COLUMN IF NOT EXISTS `media_path` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `mime_type` VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS `visible_to` ENUM('all') NOT NULL DEFAULT 'all',
  ADD COLUMN IF NOT EXISTS `options` JSON NULL,
  ADD COLUMN IF NOT EXISTS `reponse_correcte` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `date_limite` DATETIME NULL;

ALTER TABLE `stories`
  ADD COLUMN IF NOT EXISTS `media_path` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `media_type` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `expires_at` DATETIME NULL;

ALTER TABLE `groups`
  ADD COLUMN IF NOT EXISTS `created_by` INT NULL,
  ADD COLUMN IF NOT EXISTS `type` ENUM('cardinal', 'discussion') NOT NULL DEFAULT 'discussion';

ALTER TABLE `notifications`
  ADD COLUMN IF NOT EXISTS `type` VARCHAR(50) NOT NULL DEFAULT 'system',
  ADD COLUMN IF NOT EXISTS `message` TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS `payload` JSON NULL,
  ADD COLUMN IF NOT EXISTS `is_read` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `audit_logs`
  MODIFY COLUMN `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;